apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shift-scheduler
  name: deploy-shift-scheduler
spec:
  replicas: 5
  selector:
    matchLabels:
      app: shift-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: shift-scheduler
    spec:
      containers:
      - image: mybanez1/shift-scheduler
        name: shift-scheduler
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: vol-database
          mountPath: /shift-scheduler
      volumes:
      - name: vol-database
        persistentVolumeClaim:
          claimName: pvc-shift-scheduler
