apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-database
spec:
  storageClassName: local-storage 
  accessModes: 
  - ReadWriteMany 
  capacity: 
    storage: 200Mi 
  hostPath: 
    path: /database
  persistentVolumeReclaimPolicy: Retain 