apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-shift-scheduler
spec: 
  storageClassName: local-storage 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 200Mi 