apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: shift-scheduler
  name: svc-nodeport
spec: 
  ports: 
  - port: 8080
    protocol: TCP 
    targetPort: 8080 
    nodePort: 30008 
  selector: 
    app: shift-scheduler
  type: NodePort